### ISSUE TITLE
Revise Readme.md

### ISSUE THREAD

**Issue by Technorico** [JamesTimothyMeech/RNG#6]
Revise your Readme.md. 
There is a big replicated part at the bottom of the "[Main Idea and High-Level Project Overview](https://github.com/JamesTimothyMeech/RNG?tab=readme-ov-file#main-idea-and-high-level-project-overview)" chapter.

**Comment by JamesTimothyMeech** [comment]
Thanks for spotting this, I deleted the duplicated part for now!
Apologies for the replicated part, I put the readme.md together on a very short timescale. 
I'll go ahead and do a more thorough cleanup when I have some more time.

**Comment by Technorico** [comment]
Don't worry I know what means speed-running documentation, and not only, to be able to submit in time.
Now, I think I can close the issue.
